---
name: Templari Modbus Sniffer
version: dev
slug: templari_modbus_sniffer
description: "Sniffer Modbus Templari"
url: https://github.com/wergio/addon-templari-modbus-sniffer
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true
map:
  - homeassistant_config:rw
options:
  bridge_host: "192.168.1.51"
  bridge_port: 8899
  rooms:
    - id: 121
      name: "Studio"
    - id: 122
      name: "Sala"
    - id: 123
      name: "Cucina"
    - id: 124
      name: "Camera Letto Piccola"
    - id: 125
      name: "Bagno Grande"
    - id: 126
      name: "Ripostiglio"
    - id: 127
      name: "Camera Letto Matrimoniale"
    - id: 128
      name: "Bagno Piccolo"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  autogen_mqtt_entities: true
  mqtt_prefix: "templari"
  log_enabled: false
schema:
  bridge_host: str
  bridge_port: int
  rooms:
    - id: match(^\d{1,3}$)
      name: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  autogen_mqtt_entities: bool
  mqtt_prefix: str
  log_enabled: bool